//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook_Publisher
    {
        public int Book_PublisherId { get; set; }
        public int BookId { get; set; }
        public int PublisherId { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblPublisher tblPublisher { get; set; }
    }
}
