//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBook()
        {
            this.tblBook_Publisher = new HashSet<tblBook_Publisher>();
        }
    
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public int BookCategoryId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Edition { get; set; }
        public string Release_Year { get; set; }
        public int Quantity { get; set; }
        public Nullable<bool> isAvailable { get; set; }
    
        public virtual tblBookCategory tblBookCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBook_Publisher> tblBook_Publisher { get; set; }
    }
}
